/* 
 * Workspace Application API
 *
 * Application API used by Workspace Web Edition
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// VoicecallsiddeletefromconferenceData
    /// </summary>
    [DataContract]
    public partial class VoicecallsiddeletefromconferenceData :  IEquatable<VoicecallsiddeletefromconferenceData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VoicecallsiddeletefromconferenceData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VoicecallsiddeletefromconferenceData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VoicecallsiddeletefromconferenceData" /> class.
        /// </summary>
        /// <param name="DnToDrop">Reference to the telephony object that is requested to be deleted from the conference call. This parameter can be either a dn or a party_id, where party_id is the party identifier given by the switch. (required).</param>
        /// <param name="Reasons">A key/value pairs list of a data structure that provides additional information associated with this action..</param>
        /// <param name="Extensions">A key/value pairs list of additional data..</param>
        public VoicecallsiddeletefromconferenceData(string DnToDrop = default(string), List<Kvpair> Reasons = default(List<Kvpair>), List<Kvpair> Extensions = default(List<Kvpair>))
        {
            // to ensure "DnToDrop" is required (not null)
            if (DnToDrop == null)
            {
                throw new InvalidDataException("DnToDrop is a required property for VoicecallsiddeletefromconferenceData and cannot be null");
            }
            else
            {
                this.DnToDrop = DnToDrop;
            }
            this.Reasons = Reasons;
            this.Extensions = Extensions;
        }
        
        /// <summary>
        /// Reference to the telephony object that is requested to be deleted from the conference call. This parameter can be either a dn or a party_id, where party_id is the party identifier given by the switch.
        /// </summary>
        /// <value>Reference to the telephony object that is requested to be deleted from the conference call. This parameter can be either a dn or a party_id, where party_id is the party identifier given by the switch.</value>
        [DataMember(Name="dnToDrop", EmitDefaultValue=false)]
        public string DnToDrop { get; set; }
        /// <summary>
        /// A key/value pairs list of a data structure that provides additional information associated with this action.
        /// </summary>
        /// <value>A key/value pairs list of a data structure that provides additional information associated with this action.</value>
        [DataMember(Name="reasons", EmitDefaultValue=false)]
        public List<Kvpair> Reasons { get; set; }
        /// <summary>
        /// A key/value pairs list of additional data.
        /// </summary>
        /// <value>A key/value pairs list of additional data.</value>
        [DataMember(Name="extensions", EmitDefaultValue=false)]
        public List<Kvpair> Extensions { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VoicecallsiddeletefromconferenceData {\n");
            sb.Append("  DnToDrop: ").Append(DnToDrop).Append("\n");
            sb.Append("  Reasons: ").Append(Reasons).Append("\n");
            sb.Append("  Extensions: ").Append(Extensions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as VoicecallsiddeletefromconferenceData);
        }

        /// <summary>
        /// Returns true if VoicecallsiddeletefromconferenceData instances are equal
        /// </summary>
        /// <param name="other">Instance of VoicecallsiddeletefromconferenceData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VoicecallsiddeletefromconferenceData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DnToDrop == other.DnToDrop ||
                    this.DnToDrop != null &&
                    this.DnToDrop.Equals(other.DnToDrop)
                ) && 
                (
                    this.Reasons == other.Reasons ||
                    this.Reasons != null &&
                    this.Reasons.SequenceEqual(other.Reasons)
                ) && 
                (
                    this.Extensions == other.Extensions ||
                    this.Extensions != null &&
                    this.Extensions.SequenceEqual(other.Extensions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DnToDrop != null)
                    hash = hash * 59 + this.DnToDrop.GetHashCode();
                if (this.Reasons != null)
                    hash = hash * 59 + this.Reasons.GetHashCode();
                if (this.Extensions != null)
                    hash = hash * 59 + this.Extensions.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
