/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Internal.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Internal.Workspace.Model
{
    /// <summary>
    /// MediachatinteractionsidsendsystemcommandData
    /// </summary>
    [DataContract]
    public partial class MediachatinteractionsidsendsystemcommandData :  IEquatable<MediachatinteractionsidsendsystemcommandData>, IValidatableObject
    {
        /// <summary>
        /// Defines which participants in the chat can see the message.
        /// </summary>
        /// <value>Defines which participants in the chat can see the message.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VisibilityEnum
        {
            
            /// <summary>
            /// Enum All for value: All
            /// </summary>
            [EnumMember(Value = "All")]
            All = 1,
            
            /// <summary>
            /// Enum Agent for value: Agent
            /// </summary>
            [EnumMember(Value = "Agent")]
            Agent = 2,
            
            /// <summary>
            /// Enum Supervisor for value: Supervisor
            /// </summary>
            [EnumMember(Value = "Supervisor")]
            Supervisor = 3
        }

        /// <summary>
        /// Defines which participants in the chat can see the message.
        /// </summary>
        /// <value>Defines which participants in the chat can see the message.</value>
        [DataMember(Name="visibility", EmitDefaultValue=false)]
        public VisibilityEnum? Visibility { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MediachatinteractionsidsendsystemcommandData" /> class.
        /// </summary>
        /// <param name="Message">The message to send to the chat participants..</param>
        /// <param name="Visibility">Defines which participants in the chat can see the message..</param>
        /// <param name="UserData">The data of system command. This is an array of objects with the properties key, type, and value..</param>
        public MediachatinteractionsidsendsystemcommandData(string Message = default(string), VisibilityEnum? Visibility = default(VisibilityEnum?), List<Kvpair> UserData = default(List<Kvpair>))
        {
            this.Message = Message;
            this.Visibility = Visibility;
            this.UserData = UserData;
        }
        
        /// <summary>
        /// The message to send to the chat participants.
        /// </summary>
        /// <value>The message to send to the chat participants.</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }


        /// <summary>
        /// The data of system command. This is an array of objects with the properties key, type, and value.
        /// </summary>
        /// <value>The data of system command. This is an array of objects with the properties key, type, and value.</value>
        [DataMember(Name="userData", EmitDefaultValue=false)]
        public List<Kvpair> UserData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediachatinteractionsidsendsystemcommandData {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  UserData: ").Append(UserData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MediachatinteractionsidsendsystemcommandData);
        }

        /// <summary>
        /// Returns true if MediachatinteractionsidsendsystemcommandData instances are equal
        /// </summary>
        /// <param name="input">Instance of MediachatinteractionsidsendsystemcommandData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MediachatinteractionsidsendsystemcommandData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Visibility == input.Visibility ||
                    (this.Visibility != null &&
                    this.Visibility.Equals(input.Visibility))
                ) && 
                (
                    this.UserData == input.UserData ||
                    this.UserData != null &&
                    this.UserData.SequenceEqual(input.UserData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.Visibility != null)
                    hashCode = hashCode * 59 + this.Visibility.GetHashCode();
                if (this.UserData != null)
                    hashCode = hashCode * 59 + this.UserData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
