/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 9.0.000.23.2279
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Internal.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Internal.Workspace.Model
{
    /// <summary>
    /// MediachatinteractionsidconsultbyqueueData
    /// </summary>
    [DataContract]
    public partial class MediachatinteractionsidconsultbyqueueData :  IEquatable<MediachatinteractionsidconsultbyqueueData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediachatinteractionsidconsultbyqueueData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MediachatinteractionsidconsultbyqueueData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MediachatinteractionsidconsultbyqueueData" /> class.
        /// </summary>
        /// <param name="Queue">The name of the queue where the Workspace API should send the consult invite. (required).</param>
        public MediachatinteractionsidconsultbyqueueData(string Queue = default(string))
        {
            // to ensure "Queue" is required (not null)
            if (Queue == null)
            {
                throw new InvalidDataException("Queue is a required property for MediachatinteractionsidconsultbyqueueData and cannot be null");
            }
            else
            {
                this.Queue = Queue;
            }
        }
        
        /// <summary>
        /// The name of the queue where the Workspace API should send the consult invite.
        /// </summary>
        /// <value>The name of the queue where the Workspace API should send the consult invite.</value>
        [DataMember(Name="queue", EmitDefaultValue=false)]
        public string Queue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediachatinteractionsidconsultbyqueueData {\n");
            sb.Append("  Queue: ").Append(Queue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MediachatinteractionsidconsultbyqueueData);
        }

        /// <summary>
        /// Returns true if MediachatinteractionsidconsultbyqueueData instances are equal
        /// </summary>
        /// <param name="input">Instance of MediachatinteractionsidconsultbyqueueData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MediachatinteractionsidconsultbyqueueData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Queue == input.Queue ||
                    (this.Queue != null &&
                    this.Queue.Equals(input.Queue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Queue != null)
                    hashCode = hashCode * 59 + this.Queue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
