/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Internal.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Internal.Workspace.Model
{
    /// <summary>
    /// MediachatinteractionsidinviteData
    /// </summary>
    [DataContract]
    public partial class MediachatinteractionsidinviteData :  IEquatable<MediachatinteractionsidinviteData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediachatinteractionsidinviteData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MediachatinteractionsidinviteData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MediachatinteractionsidinviteData" /> class.
        /// </summary>
        /// <param name="AgentId">EmployeeId of the target agent. (required).</param>
        public MediachatinteractionsidinviteData(string AgentId = default(string))
        {
            // to ensure "AgentId" is required (not null)
            if (AgentId == null)
            {
                throw new InvalidDataException("AgentId is a required property for MediachatinteractionsidinviteData and cannot be null");
            }
            else
            {
                this.AgentId = AgentId;
            }
        }
        
        /// <summary>
        /// EmployeeId of the target agent.
        /// </summary>
        /// <value>EmployeeId of the target agent.</value>
        [DataMember(Name="agentId", EmitDefaultValue=false)]
        public string AgentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediachatinteractionsidinviteData {\n");
            sb.Append("  AgentId: ").Append(AgentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MediachatinteractionsidinviteData);
        }

        /// <summary>
        /// Returns true if MediachatinteractionsidinviteData instances are equal
        /// </summary>
        /// <param name="input">Instance of MediachatinteractionsidinviteData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MediachatinteractionsidinviteData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AgentId == input.AgentId ||
                    (this.AgentId != null &&
                    this.AgentId.Equals(input.AgentId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AgentId != null)
                    hashCode = hashCode * 59 + this.AgentId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
