/* 
 * Workspace API
 *
 * Agent API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Internal.Workspace.Client.SwaggerDateConverter;

namespace Genesys.Internal.Workspace.Model
{
    /// <summary>
    /// UcsinteractionsididentifycontactData
    /// </summary>
    [DataContract]
    public partial class UcsinteractionsididentifycontactData :  IEquatable<UcsinteractionsididentifycontactData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UcsinteractionsididentifycontactData" /> class.
        /// </summary>
        /// <param name="CreateContactEnabled">Indicates if a contact should be created if no matching contact found.</param>
        public UcsinteractionsididentifycontactData(bool? CreateContactEnabled = default(bool?))
        {
            this.CreateContactEnabled = CreateContactEnabled;
        }
        
        /// <summary>
        /// Indicates if a contact should be created if no matching contact found
        /// </summary>
        /// <value>Indicates if a contact should be created if no matching contact found</value>
        [DataMember(Name="createContactEnabled", EmitDefaultValue=false)]
        public bool? CreateContactEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UcsinteractionsididentifycontactData {\n");
            sb.Append("  CreateContactEnabled: ").Append(CreateContactEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UcsinteractionsididentifycontactData);
        }

        /// <summary>
        /// Returns true if UcsinteractionsididentifycontactData instances are equal
        /// </summary>
        /// <param name="other">Instance of UcsinteractionsididentifycontactData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UcsinteractionsididentifycontactData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CreateContactEnabled == other.CreateContactEnabled ||
                    this.CreateContactEnabled != null &&
                    this.CreateContactEnabled.Equals(other.CreateContactEnabled)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CreateContactEnabled != null)
                    hash = hash * 59 + this.CreateContactEnabled.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
